### ISSUE TITLE
How to set the profile pins using the software - urgent request

### ISSUE THREAD

**Issue by Hanros94** [Schlabonski/evalcontrol#6]
Hi Fabian

I only have one problem outstanding. How do you set the profile pins to be on and off using the python module. As it is done using the proprietary software without any external signals to the header pins surely it must be possible using the python module. I want to be able to upload frequency profiles regularly and activate the modulation mode.

**Comment by Schlabonski** [comment]
Hi Roshan,

I haven't used this feature yet as my goal was to have fast real time control over the frequencuies using an external logic signal. I'm sure that it is possible using the communcation with the cyusb chip. Are you planning on externally reading the state of the pins P0-P3? Else I wouldn't see an advantage in using them, instead of just writing a new frequency to the frequency register 0 of the respective channel, as it would take roughly the same time.

Cheers

Fabian
